"""
CrowdShield AI - SpatioTemporalCrowdPredictor
================================================
A hybrid short-term forecasting engine combining:

  1. Flow-conservation model:   N(t+dt) ~= N(t) + inflow*dt - outflow*dt
  2. Feature-based ML predictor: gradient-boosted regressor (if xgboost/
     sklearn are available) trained on synthetic trajectories generated by
     this very simulator; falls back to a transparent weighted heuristic
     if no ML backend is installed, so the app never crashes or degrades
     silently.
  3. Graph propagation: neighbour inflow/outflow influence bounded by
     downstream capacity, applied iteratively per horizon.

The public surface (`predict_node`, `predict_all`) is stable regardless of
which internal backend is active, so a future GNN can be dropped in behind
this same interface without touching callers.
"""
from __future__ import annotations

from typing import Dict, List

from . import config
from .graph_model import Node, StadiumGraph

try:
    from sklearn.ensemble import GradientBoostingRegressor
    _ML_AVAILABLE = True
except Exception:  # pragma: no cover - environment dependent
    _ML_AVAILABLE = False


FEATURE_NAMES = [
    "current_density", "density_growth", "inflow", "outflow", "velocity_proxy",
    "velocity_change", "counterflow_ratio", "neighbor_density", "neighbor_flow",
    "edge_utilization", "node_capacity", "downstream_capacity",
]


def _clip(x, lo=0.0, hi=4.5):
    return max(lo, min(hi, x))


class SpatioTemporalCrowdPredictor:
    """Predicts density/flow/risk-relevant features per node for several horizons."""

    def __init__(self):
        self.model = None
        self.trained = False
        if _ML_AVAILABLE:
            self.model = GradientBoostingRegressor(
                n_estimators=60, max_depth=3, learning_rate=0.1, random_state=config.DEMO_RANDOM_SEED
            )
            self._bootstrap_train()

    # -- synthetic bootstrap training (keeps the demo self-contained/offline) --
    def _bootstrap_train(self):
        import random
        rng = random.Random(config.DEMO_RANDOM_SEED)
        X, y = [], []
        for _ in range(600):
            density = rng.uniform(0, 4)
            growth = rng.uniform(-0.5, 1.5)
            inflow = rng.uniform(0, 20)
            outflow = rng.uniform(0, 20)
            vel = rng.uniform(0.2, 1.6)
            vel_change = rng.uniform(-0.5, 0.2)
            counterflow = rng.uniform(0, 0.4)
            neigh_density = rng.uniform(0, 4)
            neigh_flow = rng.uniform(0, 20)
            util = rng.uniform(0, 1.3)
            cap = rng.uniform(4, 10)
            down_cap = rng.uniform(0, 10)
            feats = [density, growth, inflow, outflow, vel, vel_change, counterflow,
                     neigh_density, neigh_flow, util, cap, down_cap]
            # ground-truth generator: physically-motivated future density (30s horizon)
            net = (inflow - outflow) / max(cap, 1.0)
            future = density + net * 0.9 + growth * 0.4 + counterflow * 0.6 - max(0, down_cap - 5) * 0.02
            future = _clip(future)
            X.append(feats)
            y.append(future)
        try:
            self.model.fit(X, y)
            self.trained = True
        except Exception:
            self.trained = False

    # -- feature extraction -----------------------------------------------
    def _extract_features(self, sg: StadiumGraph, node: Node) -> List[float]:
        hist = node.density_history[-4:] if node.density_history else [node.current_density]
        growth = (node.current_density - hist[0]) / max(hist[0], 0.05)
        neighbors = sg.neighbors(node.id)
        neigh_density = (sum(sg.nodes[n].current_density for n in neighbors) / len(neighbors)
                          if neighbors else node.current_density)
        neigh_flow = (sum(sg.nodes[n].inflow for n in neighbors) / len(neighbors)
                      if neighbors else node.inflow)
        out_edges = sg.out_edges(node.id)
        util = (sum(e.utilization for e in out_edges) / len(out_edges)) if out_edges else 0.0
        counterflow = max((e.counterflow_ratio for e in out_edges), default=0.0)
        vel_proxy = max(0.15, 1.4 - node.current_density * 0.25)  # people slow down in dense areas
        vel_hist = getattr(node, "_prev_velocity", vel_proxy)
        vel_change = vel_proxy - vel_hist
        node._prev_velocity = vel_proxy
        downstream_cap = min((sg.nodes[n].capacity - sg.nodes[n].current_people for n in neighbors),
                              default=5.0)
        return [node.current_density, growth, node.inflow, node.outflow, vel_proxy, vel_change,
                counterflow, neigh_density, neigh_flow, util, node.capacity, downstream_cap]

    # -- public API ---------------------------------------------------------
    def predict_node(self, sg: StadiumGraph, node: Node) -> Dict[int, float]:
        """Returns {horizon_seconds: predicted_density} for all configured horizons."""
        feats = self._extract_features(sg, node)
        predictions: Dict[int, float] = {}

        # Base flow-conservation projection (physically stabilising component)
        net_rate = node.inflow - node.outflow  # people/sec

        for horizon in config.PREDICTION_HORIZONS:
            conservation_estimate = node.current_people + net_rate * horizon
            conservation_estimate = max(0.0, conservation_estimate)
            conservation_density = conservation_estimate / max(node.area_m2, 1.0)

            if self.trained:
                try:
                    ml_density = float(self.model.predict([feats])[0])
                except Exception:
                    ml_density = conservation_density
            else:
                # transparent heuristic fallback (still feature-driven, not a flat rule)
                growth = feats[1]
                counterflow = feats[6]
                ml_density = (node.current_density + net_rate / max(node.capacity, 1.0) * 0.8
                              + growth * 0.3 + counterflow * 0.5)
                ml_density = _clip(ml_density)

            # Graph-propagation blend: neighbour pressure nudges the estimate, bounded by capacity
            neighbors = sg.neighbors(node.id)
            neighbor_pressure = 0.0
            if neighbors:
                neighbor_pressure = sum(
                    max(0.0, sg.nodes[n].current_density - node.current_density) * 0.05
                    for n in neighbors
                )
            scale = min(1.0, horizon / 60.0)
            blended = (0.5 * conservation_density + 0.4 * ml_density + 0.1 * (node.current_density + neighbor_pressure))
            blended = node.current_density + (blended - node.current_density) * (0.3 + 0.7 * scale)
            predictions[horizon] = round(_clip(blended), 4)

        return predictions

    def predict_all(self, sg: StadiumGraph) -> Dict[str, Dict[int, float]]:
        return {nid: self.predict_node(sg, n) for nid, n in sg.nodes.items()}
